tag: FunctionCheck
contents:
  listOfRestrictedFuns:
    - "defaultInvalidThrowECException"
    - "defaultThrowECException"
    - "throwErr"
    - "throwExceptionV2"
    - "throwUpstreamGatewayError"
  moduleNameToCheck: "Main"
  funNameToCheck: "testParentFunction"
  conditionToCheck: []
  pathsToConsider: []
  pathsToIgnore: []
  modulesToIgnore: []