tag: FunctionCheck
contents:
  listOfRestrictedFuns:
    - "throwErr"
    - "throwException"
  moduleNameToCheck: "Main"
  funNameToCheck: "testParentFunction"
  conditionToCheck: []
  pathsToConsider: []
  pathsToIgnore: []
  modulesToIgnore: []